enum SchemaTypesReference {
  User = "user",
  Customer = "customer",
  CustomerInfo = "customerInfo",
  Token = "token",
  Category = "category",
  SubCategory = "subCategory",
  SizeCategory = "sizeCategory",
  Product = "product",
  Color = "color",
  Variant = "variant",
  GroupSize = "groupSize",
  imageSlider = "imageSlider",
  Wishlist = "wishlist",
  Shipping = "shipping",
  Offer = "offer",
  Order = "order"
}
export default SchemaTypesReference;
