import { Router } from "express";
import categoryPublicRouter from "../Category/CategoryPublicRouter";
import ProductPublicRouter from "../Product/ProductPublicRouter";
import PublicImageSliderRouter from "../ImageSlider/PublicImageSliderRouter";
import subCategoryPublicRouter from "../SubCategory/SubCategoryPublicRouter";
import PublicColorRouter from "../Color/PublicColorRouter";
import RouterEnum from "../../Utils/Routes";
import wishlistRouter from "../Wishlist/WishlistRouter";
import PublicOfferRouter from "../Offers/OffersPublicRouter";
import customerInfoRouter from "../User/CustomerInfoRouter";
import CustomerRouter from "../User/CustomerRouter";
import PublicShippingRouter from "../Shipping/PublicShippingRouter";
import PublicOrderRouter from "../Order/PublicOrderRouter";
const publicRouter = Router();
publicRouter.use(`/${RouterEnum.customer}`,CustomerRouter );
publicRouter.use(`/${RouterEnum.customerInfo}`, customerInfoRouter);
publicRouter.use(`/${RouterEnum.category}`, categoryPublicRouter);
publicRouter.use(`/${RouterEnum.subCategory}`, subCategoryPublicRouter);
publicRouter.use(`/${RouterEnum.product}`, ProductPublicRouter);
publicRouter.use(`/${RouterEnum.color}`, PublicColorRouter);
publicRouter.use(`/${RouterEnum.imageSlider}`, PublicImageSliderRouter);
publicRouter.use(`/${RouterEnum.shipping}`,PublicShippingRouter)
publicRouter.use(`/${RouterEnum.wishlist}`, wishlistRouter);
publicRouter.use(`/${RouterEnum.offers}`, PublicOfferRouter);
publicRouter.use(`/${RouterEnum.order}`, PublicOrderRouter);
export default publicRouter;