import { Router } from "express";
import * as categoryController from "../../Controller/Category/CategoryController";
import { Validation } from "../../middleware/ValidationMiddleware";
import * as CategoryValidation from "../../Validation/Category/CategoryValidation";
const categoryRouter = Router();
categoryRouter.post("/create", Validation(CategoryValidation.createCategoryValidation), categoryController.CreateNewCategory);
categoryRouter.patch("/update/:_id", Validation(CategoryValidation.updateCategoryValidation), categoryController.updateCategory);
categoryRouter.patch("/soft-delete/:_id", Validation(CategoryValidation.deleteCategoryValidation), categoryController.softDeleteOneCategory);
categoryRouter.delete("/hard-delete/:_id", Validation(CategoryValidation.deleteCategoryValidation), categoryController.hardDeleteOneCategory);
categoryRouter.get("/deleted", categoryController.getAllDeletedCategories);
export default categoryRouter;
