import { Router } from "express";
import * as ImageSliderController from "../../Controller/ImageSlider/ImageSliderController";
import { Validation } from "../../middleware/ValidationMiddleware";
import * as ImageSliderValidation from "../../Validation/ImageSlider/ImageSliderValidation";
const imageSliderRouter = Router();
imageSliderRouter.get("/all", ImageSliderController.getAllImageSliderSection);
imageSliderRouter.post("/create", Validation(ImageSliderValidation.createImageSliderValidation), ImageSliderController.createImageSliderSection);
imageSliderRouter.get("/:_id", Validation(ImageSliderValidation.imageSliderIdAdminValidation), ImageSliderController.getImageSliderById);
imageSliderRouter.patch("/:_id", Validation(ImageSliderValidation.updateImageSliderValidation), ImageSliderController.updateImageSliderSection);
imageSliderRouter.delete("/:_id", Validation(ImageSliderValidation.imageSliderIdAdminValidation), ImageSliderController.deleteImageSlider);
export default imageSliderRouter;
