import { Router } from "express";
const ProductRouter = Router();
import * as ProductController from "../../Controller/Product/ProductController";
import { Validation } from "../../middleware/ValidationMiddleware";
import * as ProductValidation from "../../Validation/Product/ProductValidation";
ProductRouter.post("/create", Validation(ProductValidation.createProductValidation), ProductController.CreateProduct);
ProductRouter.get("/search",Validation(ProductValidation.AdminProductSearchSchema),ProductController.SearchProducts);
ProductRouter.patch("/update/:productId", Validation(ProductValidation.updateProductValidation), ProductController.updateProduct);
ProductRouter.patch("/soft-delete/:productId", Validation(ProductValidation.ProductIdValidationSchemaForAdmin), ProductController.softDeleteProduct);
ProductRouter.patch("/restore/:productId", Validation(ProductValidation.ProductIdValidationSchemaForAdmin), ProductController.restoreProduct);
ProductRouter.delete("/hard-delete/:productId", Validation(ProductValidation.ProductIdValidationSchemaForAdmin), ProductController.hardDeleteProduct);
ProductRouter.get("/get-one-product/:productId", Validation(ProductValidation.ProductIdValidationSchemaForAdmin), ProductController.findAdminProductById);
ProductRouter.get("/get-all-products",Validation(ProductValidation.getAdminProductsValidation), ProductController.getAllProductsForAdmin);
ProductRouter.get("/get-analysis", ProductController.getAnalysis);
export default ProductRouter;