import { Router } from "express";
const ProductPublicRouter = Router();
import * as ProductController from "../../Controller/Product/ProductController";
import { Validation } from "../../middleware/ValidationMiddleware";
import * as ProductValidation from "../../Validation/Product/ProductValidation";
ProductPublicRouter.get("/search-product",ProductController.SearchProducts);
ProductPublicRouter.get("/get-one-product/:productId",Validation(ProductValidation.productIdValidationSchemaForUser) ,ProductController.getUserProductById);
ProductPublicRouter.get("/get-all-products",Validation(ProductValidation.getUserAllProductsValidation),ProductController.getAllProductsForUser);
ProductPublicRouter.post("/products-stock",ProductController.findProductsStock);
export default ProductPublicRouter;