import { Router } from "express";
const ProductRouter = Router();
import * as ProductController from "../../Controller/Product/ProductController";
import { Validation } from "../../middleware/ValidationMiddleware";
import * as ProductValidation from "../../Validation/Product/ProductValidation";
ProductRouter.post("/create", Validation(ProductValidation.createProductValidation), ProductController.CreateProduct);
ProductRouter.patch("/update/:productId", Validation(ProductValidation.updateProductValidation), ProductController.updateProduct);
ProductRouter.patch("/soft-delete/:productId", Validation(ProductValidation.ProductIdValidationSchema), ProductController.softDeleteProductController);
ProductRouter.patch("/restore/:_id", Validation(ProductValidation.ProductIdValidationSchema), ProductController.restoreOneProduct);
ProductRouter.delete("/hard-delete/:productId", Validation(ProductValidation.ProductIdValidationSchema), ProductController.hardDeleteProductController);
ProductRouter.get("/get-one-product/:productId", Validation(ProductValidation.getProductByIdValidation), ProductController.findAdminProductById);
ProductRouter.get("/get-all-products", Validation(ProductValidation.getAdminProductsValidation), ProductController.getAdminProductsByFilters);
//ProductRouter.get("/get-analysis", ProductController.getAnalysis);
export default ProductRouter;