enum RouterEnum {
  authentication = "authentication",
  user = "user",
  customer = "customer",
  customerInfo = "customer-info",
  category = "category",
  subCategory = "sub-category",
  sizeCategory = "group-size",
  product = "product",
  variant = "variant",
  color = "color",
  public = "public",
  aws = "aws",
  imageSlider = "hero-section",
  wishlist = "wishlist",
  shipping = "shipping",
  offers = "offers",
  order = "order",
  socialReview = "social-review"
}
export default RouterEnum;
